### ISSUE TITLE
Ability to use request in ST_EXPLODE

### ISSUE THREAD

**Issue by nicolas-f** [irstv/H2GIS#418]
Should be cool if we could use request in ST_EXPLODE parameter like this:

```mysql
SELECT THE_GEOM FROM ST_EXPLODE('SELECT THE_GEOM FROM MYTABLE');
```

**Comment by ebocher** [comment]
A workarround will be to create a view on SELECT THE_GEOM FROM MYTABLE and next offer the name of view to the st_explode.
