### ISSUE TITLE
OSMDownloader and OSMRead don't work correctly.

### ISSUE THREAD

**Issue by ebocher** [irstv/H2GIS#441]
This instruction produces an empty node table while the xml file contains several nodes.

call ST_OSMDOWNLOADER('POLYGON ((-2.130192869203905 47.633867888575935, -2.1318522937536533 47.640236490902, -2.1233757737562904 47.64032618952631, -2.1196532808473956 47.63960860053182, -2.1203708698418815 47.63377818995163, -2.130192869203905 47.633867888575935))'::geometry, '/tmp/test.xml');
call osmread('/tmp/test.xml');

@gpetit

**Comment by ebocher** [comment]
It works in H2GIS. See #452

**Comment by ebocher** [comment]
but not in OrbisGIS ....

**Comment by gpetit** [comment]
I'm using OrbisGIS V5.1 snapshot from 09/04/2015 and H2GIS (dist 1.1.1) from 09/04/2015.

In both cases, the tables are empty.

**Comment by gpetit** [comment]
In fact this issue is linked to the OSM file extension.
OSMRead is not able to read .xml file.
So, in the ST_Downloader step, the user HAS TO specify an .osm file

**Comment by ebocher** [comment]
Fix #489
