### ISSUE TITLE
H2GIS standalone

### ISSUE THREAD

**Issue by ebocher** [irstv/H2GIS#447]
The command maven clean install -P standalone does not contain the run.sh as noted on the wiki page.

**Comment by nicolas-f** [comment]
What is the url of the concerned wiki page ?

**Comment by ebocher** [comment]
the main page

**Comment by ebocher** [comment]
"In the folder h2-dist/target/ you will find a zip file h2gis-standalone-bin.zip that contain a run.sh "

**Comment by nicolas-f** [comment]
Updated
