### ISSUE TITLE
Web Documentation of ST_SunPosition and ST_GeometryShadow

### ISSUE THREAD

**Issue by nicolas-f** [irstv/H2GIS#464]
Write the h2gis.org documentation for new SQL functions:
 - [x] ST_GeometryShadow
 - [x] ST_SunPosition

**Comment by ebocher** [comment]
Add also

 - [ ] ST_LineMerge
 - [ ] ST_Accum
 - [ ] ST_SideBuffer

**Comment by gpetit** [comment]
@nicolas-f @ebocher I think you can close this issue now :-)
