### ISSUE TITLE
downloadOSMFileAndImport() in OSMImportTest

### ISSUE THREAD

**Issue by obonin** [irstv/H2GIS#472]
in the Test package of h2spatial-ext, OSMImportTest.

The OSM file that is downloaded has been updated on the server: the node count is no more 3243 but 3245. It must be corrected in downloadOSMFileAndImport() in order to compile.
OB

**Comment by ebocher** [comment]
@obonin 
thanks a lot.
I will look asap.

**Comment by ebocher** [comment]
done with #476

**Comment by ebocher** [comment]
Please close the ticket if it's ok for you.
