### ISSUE TITLE
Rename ST_CollectExtract to ST_CollectionExtract

### ISSUE THREAD

**Issue by gpetit** [irstv/H2GIS#475]
Considering that the PostGIS's function ST_CollectionExtract already exists (see http://postgis.net/docs/manual-2.0/ST_CollectionExtract.html), we should rename our H2GIS function ST_CollectExtract (https://github.com/irstv/H2GIS/blob/c4b82370bd920e94b3a22b9b125667d8e373d6f9/h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/edit/ST_CollectExtract.java) to ST_CollectionExtract

**Comment by gpetit** [comment]
and @ebocher in the function's comments you wrote "Only points, lines and polygons are supported."

--> what do you mean ? I tried with multigeometries or geometrycollection and it works well.

**Comment by ebocher** [comment]
Done #477
