### ISSUE TITLE
Web Documentation for SQL functions

### ISSUE THREAD

**Issue by gpetit** [irstv/H2GIS#478]
Produce the web documentation for

 - [x] ST_CollectExtract
 - [x] ST_OSMDownloader
 - [x] ST_ProjectPoint
 - [x] ST_SideBuffer
 - [x] ST_RingSideBuffer
 - [x] ST_RingBuffer
 - [x] ST_Explode (update doc)
 - [x] ST_LineIntersector

This issue is linked with #464

**Comment by ebocher** [comment]
Merci ;-)
