### ISSUE TITLE
Pblm with ST_GeometryShadow

### ISSUE THREAD

**Issue by gpetit** [irstv/H2GIS#493]
I have a problem with the last paramater (the boolean value that allows or not to merge polygons) of the ST_GeometryShadow function (see https://github.com/irstv/H2GIS/blob/e2bc440c042d38d422a95d0a5a969f1939bbe13f/h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/earth/ST_GeometryShadow.java)

I have one small table, with two buildings
```
DROP TABLE IF EXISTS building, building_shadow;
CREATE TABLE building (the_geom geometry, height double);
INSERT INTO building values('POLYGON((356090.9 6693096.6, 356132.1 6693112.3, 356147.4 6693071.3, 356105.8 6693055.8, 356090.9 6693096.6))', 6);
INSERT INTO building values('POLYGON((356160 6693075.8, 356144.7 6693116.9, 356185.8 6693132.4, 356201.2 6693091.6, 356160 6693075.8))', 10);
```
Then I compute the shadow with this instruction
```
CREATE TABLE building_shadow AS SELECT ST_Geometryshadow(the_geom, ST_SunPosition('POINT(-1.54544 47.24961)','2015-01-30 10:00:00+01:00'), height) FROM building;
```
The boolean parameter is not used ... and it works well.

Now I want to use this parameter, so I execute
```
CREATE TABLE building_shadow AS SELECT ST_Geometryshadow(the_geom, ST_SunPosition('POINT(-1.54544 47.24961)','2015-01-30 10:00:00+01:00'), height, 1) FROM building;
```

Here I obtain this error message
```
Execute request 5/5: CREATE TABLE building_shadow AS SELECT ST_Geometryshadow(the_geom, ST_SunPosition('POINT(-1.54544 47.24961)','2015-01-30 10:00:00+01:00'), height, 1) FROM building
Get rowset without opening it
java.sql.SQLException: Table "BUILDING" not found.
Data conversion error converting "POINT (2.3033385162216393 0.1923377275871038)"; SQL statement:
CREATE TABLE building_shadow AS SELECT ST_Geometryshadow(the_geom, ST_SunPosition('POINT(-1.54544 47.24961)','2015-01-30 10:00:00+01:00'), height, 1) FROM building [22018-186]
Cannot compute layer envelope:
The table "BUILDING_SHADOW" does not contain a Geometry field, then the extent cannot be computed
```

Have you any idea why I have this message. Maybe I'm wrong with the use of this parameter ?

@ebocher

**Comment by nicolas-f** [comment]
Try


CREATE TABLE building_shadow AS SELECT ST_Geometryshadow(the_geom, ST_SunPosition('POINT(-1.54544 47.24961)','2015-01-30 10:00:00+01:00'), height, 1) **the_geom** FROM building;

**Comment by ebocher** [comment]
+100 @nicolas-f 
This is problem due to the name of the column.

**Comment by nicolas-f** [comment]
Ah you mix lot of errors.

use this query
```sql
CREATE TABLE building_shadow AS SELECT ST_Geometryshadow(the_geom, ST_SunPosition('POINT(-1.54544 47.24961)'::geometry,'2015-01-30 10:00:00+01:00'), height, 1) FROM building
```

**Comment by ebocher** [comment]
This signature is not supported.
Use
CREATE TABLE building_shadow AS SELECT ST_Geometryshadow(the_geom, ST_SunPosition('POINT(-1.54544 47.24961)'::geometry,'2015-01-30 10:00:00+01:00'), height) as the_geom FROM building

**Comment by ebocher** [comment]
You have

* computeShadow(Geometry geometry, Geometry sunPosition, double height)
* computeShadow(Geometry geometry, double azimuth, double altitude, double height) 
* computeShadow(Geometry geometry, double azimuth, double altitude, double height, boolean doUnion)

**Comment by gpetit** [comment]
Ok I see. it's due to the signature.
So I executed this
```
CREATE TABLE building_shadow2 AS SELECT ST_Geometryshadow(the_geom, ST_X(ST_SunPosition('POINT(-1.54544 47.24961)','2015-01-30 10:00:00+01:00')), ST_Y(ST_SunPosition('POINT(-1.54544 47.24961)','2015-01-30 10:00:00+01:00')), height,0) as the_geom FROM building;
```
and it works well.

Note that ::geometry is not needed

**Comment by gpetit** [comment]
Thx guys :-)
