### ISSUE TITLE
H2GIS 1.3 X documentation

### ISSUE THREAD

**Issue by ebocher** [irstv/H2GIS#501]
Produce the web documentation for

 - [x] ST_MaxDistance,
 - [x] ST_LongestLine,
 - [x] ST_FlipCoordinates.

Update documentation for

 - [x] ST_PointFromText,
 - [x] ST_MPointFromText,
 - [x] ST_LineFromText,
 - [x] ST_MLineFromText,
 - [x] ST_PolyFromText,
 - [x] ST_MPolyFromText,
 - [x] ST_PolyFromWKB,
 - [x] ST_LineFromWKB
 - [x] ST_PointFromWKB

Add the text : If an SRID is not specified, it defaults to 0.

**Comment by gpetit** [comment]
@ebocher  This issue can be closed
