### ISSUE TITLE
H2GIS ST_Delaunay VS PostGIS ST_DelaunayTriangles

### ISSUE THREAD

**Issue by gpetit** [irstv/H2GIS#519]
If we compare ST_Delaunay from H2GIS and ST_DelaunayTriangles PostGIS we don't have the same signatures

ST_Delaunay (https://github.com/irstv/H2GIS/blob/master/h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/mesh/ST_Delaunay.java)
```
ST_DELAUNAY(GEOMETRY)
ST_DELAUNAY(GEOMETRY, FLAG)
ST_DELAUNAY(GEOMETRY, FLAG, TOLERANCE)
``` 
and

ST_DelaunayTriangles (http://postgis.net/docs/ST_DelaunayTriangles.html) 
```
ST_DelaunayTriangles(GEOMETRY)
ST_DelaunayTriangles(GEOMETRY, TOLERANCE)
ST_DelaunayTriangles(GEOMETRY, TOLERANCE, FLAG)
``` 

Is it normal ?

@ebocher @nicolas-f 

Doc under construction at #479

**Comment by ebocher** [comment]
I'm not in favor of postgis semantic. Because a delaunay triangulation is always a set of triangles, moreover the postgis function returns more than single triangles.
So I propose to keep the H2GIS signature.

**Comment by gpetit** [comment]
Ok for me
