### ISSUE TITLE
ST_Delaunay - quality parameter works only with 2.5D

### ISSUE THREAD

**Issue by gpetit** [irstv/H2GIS#520]
When you use ST_Delaunay, you have this signature
```
GEOMETRY ST_DELAUNAY(GEOMETRY geom, INTEGER flag, DOUBLE quality)
```
This signature works ONLY if the geometry is in 2.5D (with a Z value).

It seems that @nicolas-f will resolve this problem, with poly2tri ...

@ebocher

**Comment by ebocher** [comment]
We will Nicolas's super code

**Comment by gpetit** [comment]
You mean "wait" ?

**Comment by ebocher** [comment]
a yes

**Comment by ebocher** [comment]
This issue will be fixed with the last triangulation library.
